/*
    Cinnamon UCI chess engine
    Copyright (C) Giuseppe Cannella

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

#include "../perft/task/Perft.h"
#include "../namespaces/def.h"

using namespace _def;

class GetOptTask {
public:

    static void parse(int argc, char **argv) {
        vector<string> params;
        for (int i = 1; i < argc; i++) {
            params.push_back(argv[i]);
        }
        assert(params[0] == "--task");
        //--task -start /home/geko/master_autogenerated.ini /home/geko/workspace/Auriga/src/conf/engine/stockfish.auriga.ini BB7CFAA9-48D6-3EA9-A601-CFA834C3E0C1
        if (params.size() == 5 && params[1] == "-start") {
            string master = params[2];
            if (!FileUtil::fileExists(master)) {
                error("file not found ", master);
                exit(0);
            }
            string engine = params[3];
            if (!FileUtil::fileExists(engine)) {
                error("file not found ", engine);
                exit(0);
            }
            string taskUUID = params[4];
            _perft::Perft perft(taskUUID,master, engine);
            perft.calculate();

        } else {
            cout << "err" << endl;//TODO
        }
    }
};



