/*
    Cinnamon UCI chess engine
    Copyright (C) Giuseppe Cannella

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#pragma once

#include "../perft/node/Perft.h"
#include "../namespaces/def.h"

using namespace _def;

class GetOptNode {
public:

    static void parse(int argc, char **argv) {
        vector<string> params;
        for (int i = 1; i < argc; i++) {
            params.push_back(argv[i]);
        }
        assert(params[0] == "--node");
        //--node -start /home/geko/master_autogenerated.ini /home/geko/workspace/Auriga/src/conf/engine/stockfish.auriga.ini BB7CFAA9-48D6-3EA9-A601-CFA834C3E0C1
        if (params.size() == 5 && params[1] == "-start") {
            string master = params[2];
            string engine = params[3];
            string nodeUUID = params[4];
            Perft perft(master,engine);
            perft.calculate(nodeUUID);

            cout <<"a";
        } else {
            cout << "err" << endl;
        }
    }
};



